services:
    app.strategy:
        class:     AppBundle\Services\Strategy\FactoryStrategies
        arguments:

    app.method:
        class:     AppBundle\Services\Method\FactoryMethod
        arguments:

    app.strategy_manager:
        class: AppBundle\Services\StrategyManager
        arguments: ["@service_container"]

    app.matrix_manager:
        class: AppBundle\Services\MatrixManager
        arguments: ["@service_container"]

    app.task_manager:
        class: AppBundle\Services\Task\TaskManager
        arguments: ['@service_container', '@doctrine.orm.entity_manager']