services:
    app.strategy:
        class:     AppBundle\Services\Strategy\FactoryStrategies
        arguments:

    app.strategy_manager:
        class: AppBundle\Services\StrategyManager
        arguments: ["@service_container"]